# Module

 1) Write a Python program to calculate number of days between two dates. Hint: use Datetime package/module.

Sample dates : (2014, 7, 2), (2014, 7, 11)

In [1]:
import datetime

def days_between(date1, date2):
  # Convert the dates to datetime objects
  d1 = datetime.datetime(*date1)
  d2 = datetime.datetime(*date2)

  # Calculate the difference between the two dates and return the result
  return abs((d2 - d1).days)

# Example usage
print(days_between((2014, 7, 2), (2014, 7, 11)))  


9


# Functions

1) Write a Python program to get the volume of a sphere with radius 6.

In [2]:
import math

def get_volume(radius):
  volume = (4/3) * math.pi * (radius ** 3)
  return volume

radius = 6
volume = get_volume(radius)
print(f"The volume of a sphere with radius {radius} is {volume:.2f}.")


The volume of a sphere with radius 6 is 904.78.


2. Write a Python program to calculate the sum of three given numbers, if the values are equal then return three times of their sum hint: write User defined functions

In [3]:
def sum_and_triple(num1, num2, num3):
  sum = num1 + num2 + num3
  if num1 == num2 and num2 == num3:
    return sum * 3
  else:
    return sum

num1 = 4
num2 = 5
num3 = 6
result = sum_and_triple(num1, num2, num3)
print(result)

num1 = 3
num2 = 3
num3 = 3
result = sum_and_triple(num1, num2, num3)
print(result)


15
27


3. Write a Python program to count the number 4 in a given list.

List = [1,4,6,8,4,9,4]

In [4]:
def count_4(numbers):
  count = 0
  for number in numbers:
    if number == 4:
      count += 1
  return count

numbers = [1,4,6,8,4,9,4]
count = count_4(numbers)
print(f"The number 4 appears {count} times in the list.")


The number 4 appears 3 times in the list.


4. Write a Python program to print all even numbers from a given numbers list in the same order and stop the printing if any numbers that come after 237 in the sequence. Go to the editorSample numbers list :

399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,

815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,

958,743, 527]

In [5]:
numbers = [399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
           815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
           958,743, 527]

for number in numbers:
  if number == 237:
    print("Stopping the printing because 237 is found.")
    break
  elif number % 2 == 0:
    print(number)


162
758
918
Stopping the printing because 237 is found.


5. Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included)

In [6]:
def find_numbers(start, end):
  result = []
  for number in range(start, end+1):
    if number % 7 == 0 and number % 5 == 0:
      result.append(number)
  return result

start = 1500
end = 2700
result = find_numbers(start, end)
print(result)


[1505, 1540, 1575, 1610, 1645, 1680, 1715, 1750, 1785, 1820, 1855, 1890, 1925, 1960, 1995, 2030, 2065, 2100, 2135, 2170, 2205, 2240, 2275, 2310, 2345, 2380, 2415, 2450, 2485, 2520, 2555, 2590, 2625, 2660, 2695]


6.Write a Python program that prints all the numbers from 0 to 6 except 3 and 6.

Note : Use 'continue' statement.

In [7]:
for number in range(0, 7):
  if number == 3 or number == 6:
    continue
  print(number)


0
1
2
4
5


7.Write a Python program to get the Fibonacci series between 0 to 50.

In [8]:
def get_fibonacci_series(start, end):
  result = []
  a, b = 0, 1
  while a <= end:
    if a >= start:
      result.append(a)
    a, b = b, a+b
  return result

start = 0
end = 50
result = get_fibonacci_series(start, end)
print(result)


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


9. Write a Python function that takes a list and returns a new list with unique elements of the first list.

Sample List : [1,2,3,3,3,3,4,5]

Unique List : [1, 2, 3, 4, 5]

In [9]:
def get_unique_list(numbers):
  unique_numbers = []
  for number in numbers:
    if number not in unique_numbers:
      unique_numbers.append(number)
  return unique_numbers

numbers = [1,2,3,3,3,3,4,5]
unique_numbers = get_unique_list(numbers)
print(unique_numbers)


[1, 2, 3, 4, 5]


# String

 Write a Python program to concatenate all elements in a list into a string and return it.

In [11]:
def concatenate_list_elements(list):
  result = ""
  for element in list:
    result += str(element)
  return result

# Example usage
list = [1, 2, 3, 4, 5]
print(concatenate_list_elements(list))


12345


# Dictionary

Write a Python script to concatenate following dictionaries to create a new one.

Sample Dictionary :

dic1={1:10, 2:20}

dic2={3:30, 4:40}

dic3={5:50,6:60}

In [12]:
# Initialize the dictionaries
dic1 = {1: 10, 2: 20}
dic2 = {3: 30, 4: 40}
dic3 = {5: 50, 6: 60}

# Concatenate the dictionaries
new_dic = {}
new_dic.update(dic1)
new_dic.update(dic2)
new_dic.update(dic3)

# Print the new dictionary
print(new_dic) 


{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


# Series

Write a Python program to add, subtract, multiple and divide two Pandas Series.

Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [13]:
import pandas as pd

# Initialize the Series
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

# Add the Series
s3 = s1 + s2
print("Addition:")
print(s3) 

# Subtract the Series
s4 = s1 - s2
print("Subtraction:")
print(s4) 

# Multiply the Series
s5 = s1 * s2
print("Multiplication:")
print(s5)  

# Divide the Series
s6 = s1 / s2
print("Division:")
print(s6)  


Addition:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# Data Frames

Write a Pandas program to select the specified columns and rows from a given data frame. Go to the editorSample Python dictionary data and list labels:

Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],

qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [14]:
import pandas as pd
import numpy as np

# Create the data frame
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

# Select the specified columns and rows
df_subset = df[['name', 'score']].loc[['b', 'd', 'f', 'g']]

# Print the resulting data frame
print(df_subset)


      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5


# Basic Programs

 1. Write Python Programs to use various operators in Python

In [16]:
# Addition
print(2 + 3)  # Output: 5

# Subtraction
print(5 - 3)  # Output: 2

# Multiplication
print(2 * 3)  # Output: 6

# Division
print(6 / 3)  # Output: 2.0

# Modulus (remainder)
print(7 % 3)  # Output: 1

# Exponentiation
print(2 ** 3)  # Output: 8

# Floor division
print(7 // 3)  # Output: 2


5
2
6
2.0
1
8
2


 2. Create list of elements and slice and dice it


In [17]:
# Create a list of elements
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Access the first element of the list
print(my_list[0]) 

# Access the last element of the list
print(my_list[-1])  

# Access the second to fifth elements of the list (slicing)
print(my_list[1:5]) 

# Access every second element of the list (slicing with step)
print(my_list[::2]) 

# Reverse the list (slicing with negative step)
print(my_list[::-1]) 


0
9
[1, 2, 3, 4]
[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


3. Using while loop accept numbers until sum of numbers is less than 100


In [21]:
# Initialize the sum and the list of numbers
sum = 0
numbers = []

# Continuously accept numbers until the sum is less than 100
while sum < 100:
  # Read a number from the user
  number = int(input("Enter a number: "))
  
  # Add the number to the sum and the list of numbers
  sum += number
  numbers.append(number)

# Print the list of numbers
print("Numbers:", numbers)

# Print the sum of the numbers
print("Sum:", sum)


Enter a number: 25
Enter a number: 25
Enter a number: 25
Enter a number: 25
Numbers: [25, 25, 25, 25]
Sum: 100


4. Write a python program Read & write Excel files

In [23]:
#import pandas as pd

# Read an Excel file
#df = pd.read_excel("input.xlsx")

# Print the data frame
#print(df)

# Write the data frame to an Excel file
#df.to_excel("output.xlsx", index=False)


5.  Write a python program to scrape reviews from a commercial web site

In [24]:
#import requests
#from bs4 import BeautifulSoup

# Make an HTTP request to the web page
#response = requests.get("https://www.example.com/reviews")

# Parse the HTML content


6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [25]:
import numpy as np

# Create a 1-dimensional array with values ranging from 2 to 10
array = np.arange(2, 11)

# Reshape the array into a 3x3 matrix
matrix = np.reshape(array, (3, 3))

# Print the matrix
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [26]:
import numpy as np

# Create a list of numeric values
my_list = [1, 2, 3, 4, 5]

# Convert the list into a NumPy array
my_array = np.array(my_list)

# Print the array
print(my_array)


[1 2 3 4 5]


8. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [27]:
import numpy as np

# Create a null vector of size 10
vector = np.zeros(10)

# Print the vector
print(vector)

# Update the sixth element of the vector to 11
np.put(vector, 5, 11)

# Print the updated vector
print(vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]
